In [1]:
import sys
import pandas as pd
import numpy as np
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output

print( f"Python {sys.version}" )
print( f"Pandas {pd.__version__}" )
print( f"NumPy {np.__version__}" )
print( f"IPython {IPython.__version__}" )

Python 3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]
Pandas 3.0.5
NumPy 2.5.1
IPython 9.16.1

In [2]:
# Read from a CSV file (default delimiter is comma)
# Data type for each column is automatically detected unless otherwise specified.
# Can read from URL on internet and Local Directory as well.
df_pokemon = pd.read_csv('https://raw.githubusercontent.com/ShaileshDhama/Exploratory-Data-Analysis-On-Pokemon-Dataset/master/Complete%20Pokemon.csv')
df_pokemon.shape
df = df_pokemon

# 6. Pandas: Sort data

In [3]:
# Select a subset of DataFrame to play around
df = df_pokemon.loc[ : , ['pokedex_number', 'name','abilities', 'type1', 'type2', 'hp', 'attack', 'defense'] ]

print(df.shape)
df.head()

(801, 8)

,pokedex_number,name,abilities,type1,type2,hp,attack,defense
0,1,Bulbasaur,"['Overgrow', 'Chlorophyll']",grass,poison,45,49,49
1,2,Ivysaur,"['Overgrow', 'Chlorophyll']",grass,poison,60,62,63
2,3,Venusaur,"['Overgrow', 'Chlorophyll']",grass,poison,80,100,123
3,4,Charmander,"['Blaze', 'Solar Power']",fire,NaN,39,52,43
4,5,Charmeleon,"['Blaze', 'Solar Power']",fire,NaN,58,64,58

## 6.1 Sort by label

In [ ]:
# Reorder rows based on row's labels
# ใน pandas axis = 0 จะหมายถึง row และ axis = 1 จะหมายถึง column
# pandas สามาถ sorce by columns (axis=1) ได้ด้วย 
# ascending order (มากไปน้อย) คือ ascending=False
df.sort_index(ascending=False)  # default:axis=0, inplace=False

,pokedex_number,name,abilities,type1,type2,hp,attack,defense
800,801,Magearna,['Soul-Heart'],steel,fairy,80,95,115
799,800,Necrozma,['Prism Armor'],psychic,NaN,97,107,101
798,799,Guzzlord,['Beast Boost'],dark,dragon,223,101,53
797,798,Kartana,['Beast Boost'],grass,steel,59,181,131
796,797,Celesteela,['Beast Boost'],steel,flying,97,101,103
...,...,...,...,...,...,...,...,...
4,5,Charmeleon,"['Blaze', 'Solar Power']",fire,NaN,58,64,58
3,4,Charmander,"['Blaze', 'Solar Power']",fire,NaN,39,52,43
2,3,Venusaur,"['Overgrow', 'Chlorophyll']",grass,poison,80,100,123
1,2,Ivysaur,"['Overgrow', 'Chlorophyll']",grass,poison,60,62,63
0,1,Bulbasaur,"['Overgrow', 'Chlorophyll']",grass,poison,45,49,49

In [4]:
# Reorder columns based on column's labels
df.sort_index(axis=1)   # default:axis=0, inplace=False

,abilities,attack,defense,hp,name,pokedex_number,type1,type2
0,"['Overgrow', 'Chlorophyll']",49,49,45,Bulbasaur,1,grass,poison
1,"['Overgrow', 'Chlorophyll']",62,63,60,Ivysaur,2,grass,poison
2,"['Overgrow', 'Chlorophyll']",100,123,80,Venusaur,3,grass,poison
3,"['Blaze', 'Solar Power']",52,43,39,Charmander,4,fire,NaN
4,"['Blaze', 'Solar Power']",64,58,58,Charmeleon,5,fire,NaN
...,...,...,...,...,...,...,...,...
796,['Beast Boost'],101,103,97,Celesteela,797,steel,flying
797,['Beast Boost'],181,131,59,Kartana,798,grass,steel
798,['Beast Boost'],101,53,223,Guzzlord,799,dark,dragon
799,['Prism Armor'],107,101,97,Necrozma,800,psychic,NaN
800,['Soul-Heart'],95,115,80,Magearna,801,steel,fairy

## 6.2 Sort by value

In [ ]:
# Reorder rows based on values in a specified column
# ascending=False means sort in descending order (มากไปน้อย)
df.sort_values( by='hp', ascending=False )  # default:axis=0, inplace=False

,pokedex_number,name,abilities,type1,type2,hp,attack,defense
241,242,Blissey,"['Natural Cure', 'Serene Grace', 'Healer']",normal,NaN,255,10,10
112,113,Chansey,"['Natural Cure', 'Serene Grace', 'Healer']",normal,NaN,250,5,5
798,799,Guzzlord,['Beast Boost'],dark,dragon,223,101,53
717,718,Zygarde,"['Aura Break', 'Power Construct']",dragon,ground,216,100,121
201,202,Wobbuffet,"['Shadow Tag', 'Telepathy']",psychic,NaN,190,33,58
...,...,...,...,...,...,...,...,...
354,355,Duskull,"['Levitate', 'Frisk']",ghost,NaN,20,40,90
128,129,Magikarp,"['Swift Swim', 'Rattled']",water,NaN,20,10,55
171,172,Pichu,"['Static', 'Lightningrod']",electric,NaN,20,40,15
49,50,Diglett,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",ground,ground,10,55,30
291,292,Shedinja,['Wonder Guard'],bug,ghost,1,90,45

In [6]:
# Reorder rows based on values in many specified columns

# Sort by 'hp' first, then by 'attack'
df.sort_values( by=['hp','attack'], ascending=[False,True] )  # default:axis=0, inplace=False

,pokedex_number,name,abilities,type1,type2,hp,attack,defense
241,242,Blissey,"['Natural Cure', 'Serene Grace', 'Healer']",normal,NaN,255,10,10
112,113,Chansey,"['Natural Cure', 'Serene Grace', 'Healer']",normal,NaN,250,5,5
798,799,Guzzlord,['Beast Boost'],dark,dragon,223,101,53
717,718,Zygarde,"['Aura Break', 'Power Construct']",dragon,ground,216,100,121
201,202,Wobbuffet,"['Shadow Tag', 'Telepathy']",psychic,NaN,190,33,58
...,...,...,...,...,...,...,...,...
438,439,Mime Jr.,"['Soundproof', 'Filter', 'Technician']",psychic,fairy,20,25,45
171,172,Pichu,"['Static', 'Lightningrod']",electric,NaN,20,40,15
354,355,Duskull,"['Levitate', 'Frisk']",ghost,NaN,20,40,90
49,50,Diglett,"['Sand Veil', 'Arena Trap', 'Sand Force', 'San...",ground,ground,10,55,30
291,292,Shedinja,['Wonder Guard'],bug,ghost,1,90,45