In [1]:
import sys
import pandas as pd
import numpy as np
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output

print( f"Python {sys.version}" )
print( f"Pandas {pd.__version__}" )
print( f"NumPy {np.__version__}" )
print( f"IPython {IPython.__version__}" )

Python 3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]
Pandas 3.0.5
NumPy 2.5.1
IPython 9.16.1

In [4]:
# Read from a CSV file (default delimiter is comma)
# Data type for each column is automatically detected unless otherwise specified.
# Can read from URL on internet and Local Directory as well.
df_pokemon = pd.read_csv('https://raw.githubusercontent.com/ShaileshDhama/Exploratory-Data-Analysis-On-Pokemon-Dataset/master/Complete%20Pokemon.csv')
df_pokemon.shape
df = df_pokemon

# 4. Pandas: Select/Access data (unconditionally)

There are two main modes of accessing data in pandas:
- **Label-based indexing:** by using `df.loc[]` ใช้ได้ทั้งหลาย row หรือ cell or `df.at[]`ใช้ได้เป็นราย cell เรียนไว้เผื่อต้อง access รายเซลล์หลายๆครั้ง
- **Position-based indexing:** by using 0-based integer positions via `df.iloc[]` or `df.iat[]`

In [5]:
# Preview the dataset (just for a reminder)
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

## 4.1 Select/Access one element

To access one element, positions of both row and column must be specified.

In [6]:
# Access an element in row3 col0
# df.iloc[ row, column ]
df.iloc[ 3, 0 ]

"['Blaze', 'Solar Power']"

In [7]:
# Access an element of row3 of the specified column
df.loc[ 3, 'abilities' ]

"['Blaze', 'Solar Power']"

`df.at[]` and `df.iat[]`:
- For accessing <u>a single value</u> only.
- Same results as `df.loc[]` and `df.iloc[]`, but `df.at[]` and `df.iat[]` are faster for accessing a single value.
- Passing many row/column indices/labels (or a slice of indices/labels) to these two commands is not allowed.

In [8]:
# Access an element in row3 col0
df.iat[ 3, 0 ]

"['Blaze', 'Solar Power']"

In [9]:
# Access an element of row3 of the specified column name
df.at[ 3, 'abilities' ]

"['Blaze', 'Solar Power']"

## 4.2 Select/Access row(s)

In [10]:
# Select row3 (with all its columns) and return it as a pandas.Series
df.iloc[ 3 ]    # This equals to df.iloc[ 3, ] and df.iloc[ 3, : ] and returns pandas.Series

abilities            ['Blaze', 'Solar Power']
against_bug                               0.5
against_dark                              1.0
against_dragon                            1.0
against_electric                          1.0
against_fairy                             0.5
against_fight                             1.0
against_fire                              0.5
against_flying                            1.0
against_ghost                             1.0
against_grass                             0.5
against_ground                            2.0
against_ice                               0.5
against_normal                            1.0
against_poison                            1.0
against_psychic                           1.0
against_rock                              2.0
against_steel                             0.5
against_water                             2.0
attack                                     52
base_egg_steps                           5120
base_happiness                             70
base_total                                309
capture_rate                               45
classfication                  Lizard Pokémon
defense                                    43
experience_growth                     1059860
height_m                                  0.6
hp                                         39
japanese_name                    Hitokageヒトカゲ
name                               Charmander
percentage_male                          88.1
pokedex_number                              4
sp_attack                                  60
sp_defense                                 50
speed                                      65
type1                                    fire
type2                                     NaN
weight_kg                                 8.5
generation                                  1
is_legendary                                0
Name: 3, dtype: object

In [13]:
# Select row3 (with all its columns) and return it as a pandas.DataFrame
# วิธีนี้จะแสดงออกมาเป็น series เช่นกัน แต่จะ return เป็น dataframe
df.iloc[ [3] ]  # This equals to df.iloc[ 3:4 ] and df.iloc[ 3:4, : ] and returns pandas.DataFrame
# This equals df.iloc[ [3], ] and returns pandas.DataFrame

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0

In [14]:
# Select row0, row29, and row30
df.iloc[ [29, 0, 30] ]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
29,"['Poison Point', 'Rivalry', 'Hustle']",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,0.0,30,55,55,56,poison,NaN,20.0,1,0
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
30,"['Poison Point', 'Rivalry', 'Sheer Force']",0.5,1.0,1.0,0.0,0.5,0.5,1.0,1.0,1.0,...,0.0,31,75,85,76,poison,ground,60.0,1,0

In [15]:
# Select row2-row9 (slicing by integer indices is exclusive)
df.iloc[ 2:10 ]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
6,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
9,"['Shield Dust', 'Run Away']",1.00,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,...,50.0,10,20,20,45,bug,NaN,2.9,1,0

In [16]:
df.iloc[ 2:10:2 ]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0

In [17]:
df.loc[ 3 ]    # for the default row indices (0-based integer position), this is the same as df.iloc[3]

abilities            ['Blaze', 'Solar Power']
against_bug                               0.5
against_dark                              1.0
against_dragon                            1.0
against_electric                          1.0
against_fairy                             0.5
against_fight                             1.0
against_fire                              0.5
against_flying                            1.0
against_ghost                             1.0
against_grass                             0.5
against_ground                            2.0
against_ice                               0.5
against_normal                            1.0
against_poison                            1.0
against_psychic                           1.0
against_rock                              2.0
against_steel                             0.5
against_water                             2.0
attack                                     52
base_egg_steps                           5120
base_happiness                             70
base_total                                309
capture_rate                               45
classfication                  Lizard Pokémon
defense                                    43
experience_growth                     1059860
height_m                                  0.6
hp                                         39
japanese_name                    Hitokageヒトカゲ
name                               Charmander
percentage_male                          88.1
pokedex_number                              4
sp_attack                                  60
sp_defense                                 50
speed                                      65
type1                                    fire
type2                                     NaN
weight_kg                                 8.5
generation                                  1
is_legendary                                0
Name: 3, dtype: object

In [18]:
df.loc [ [3] ]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0

In [19]:
df[ 2:10 ]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
6,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
9,"['Shield Dust', 'Run Away']",1.00,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,...,50.0,10,20,20,45,bug,NaN,2.9,1,0

In [20]:
df[ 2 ]      # KeyError

KeyError: 2

## 4.3 Select/Access column(s)

In [21]:
df.iloc[ , 30 ]    # SyntaxError, omitting row indices isn't allowed

SyntaxError: invalid syntax (2605712922.py, line 1)

In [22]:
# Select all rows in col30
df.iloc[ : , 30 ]    # This command returns pandas.Series

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 801, dtype: str

In [23]:
# Select all rows in col30
# มีประโยชน์ตอนทำงานกับข้อมูลที่หลาย dimension เช่น 2D, 3D, 4D, ... โดยใช้ iloc จะสามารถเลือก dimensionที่ต้องการได้
# เช่น แทนที่จะเขียน array[:, :, :,30] เราสามารถเขียนเป็น df.iloc[ ... , 30 ] ได้
df.iloc[ ... , 30 ]

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 801, dtype: str

In [24]:
# Select all rows in col30
df.iloc[ : , [30] ]    # This command returns pandas.DataFrame

           name
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
796  Celesteela
797     Kartana
798    Guzzlord
799    Necrozma
800    Magearna

[801 rows x 1 columns]

In [25]:
# Select all rows in col30 and col0
df.iloc[ : , [30,0] ]

           name                    abilities
0     Bulbasaur  ['Overgrow', 'Chlorophyll']
1       Ivysaur  ['Overgrow', 'Chlorophyll']
2      Venusaur  ['Overgrow', 'Chlorophyll']
3    Charmander     ['Blaze', 'Solar Power']
4    Charmeleon     ['Blaze', 'Solar Power']
..          ...                          ...
796  Celesteela              ['Beast Boost']
797     Kartana              ['Beast Boost']
798    Guzzlord              ['Beast Boost']
799    Necrozma              ['Prism Armor']
800    Magearna               ['Soul-Heart']

[801 rows x 2 columns]

In [26]:
# Select all rows in col29, col30, and col31 (exclusive slicing for integer indices)
df.iloc[ : , 29:32 ]

        japanese_name        name  percentage_male
0    Fushigidaneフシギダネ   Bulbasaur             88.1
1     Fushigisouフシギソウ     Ivysaur             88.1
2    Fushigibanaフシギバナ    Venusaur             88.1
3        Hitokageヒトカゲ  Charmander             88.1
4         Lizardoリザード  Charmeleon             88.1
..                ...         ...              ...
796    Tekkaguyaテッカグヤ  Celesteela              NaN
797   Kamiturugiカミツルギ     Kartana              NaN
798   Akuzikingアクジキング    Guzzlord              NaN
799     Necrozmaネクロズマ    Necrozma              NaN
800      Magearnaマギアナ    Magearna              NaN

[801 rows x 3 columns]

In [27]:
# Select all rows in col29, col31, and col33 (exclusive slicing for integer indices)
df.iloc[ : , 29:34:2 ]

        japanese_name  percentage_male  sp_attack
0    Fushigidaneフシギダネ             88.1         65
1     Fushigisouフシギソウ             88.1         80
2    Fushigibanaフシギバナ             88.1        122
3        Hitokageヒトカゲ             88.1         60
4         Lizardoリザード             88.1         80
..                ...              ...        ...
796    Tekkaguyaテッカグヤ              NaN        107
797   Kamiturugiカミツルギ              NaN         59
798   Akuzikingアクジキング              NaN         97
799     Necrozmaネクロズマ              NaN        127
800      Magearnaマギアナ              NaN        130

[801 rows x 3 columns]

In [28]:
# Use dot notation to select one column whose name is specified
# This dot-notation writing is not applicable for any column whose name contains space or special character
# ถ้าตั้งชื่อ  column เป็นชื่อที่มี space หรือ special character จะไม่สามารถใช้ dot notation ได้
df.japanese_name

0      Fushigidaneフシギダネ
1       Fushigisouフシギソウ
2      Fushigibanaフシギバナ
3          Hitokageヒトカゲ
4           Lizardoリザード
             ...
796      Tekkaguyaテッカグヤ
797     Kamiturugiカミツルギ
798     Akuzikingアクジキング
799       Necrozmaネクロズマ
800        Magearnaマギアナ
Name: japanese_name, Length: 801, dtype: str

In [29]:
# Select one column whose name is specified
df[ 'name' ]    # This equals df.loc[ : , 'name' ] and returns a pandas.Series

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 801, dtype: str

In [30]:
# Select one column whose name is specified
df[ ['name'] ]  # This equals df.loc[ : , ['name'] ] and returns a pandas.DataFrame

           name
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
796  Celesteela
797     Kartana
798    Guzzlord
799    Necrozma
800    Magearna

[801 rows x 1 columns]

In [31]:
# Select any columns whose names are specified
# สามารถ slicing ได้หลาย column โดยใช้ list ของชื่อ column
# ถ้าเขียน slice แบบใช้ตัวเลขจะไม่เอาตัวสุดท้าย เช่น 0:3 จะได้ column 0,1,2 แต่ไม่เอา column 3
# แต่ถ้า slice แบบใช้ชื่อ column จะเอาตัวสุดท้ายด้วย เช่น 'name':'abilities' จะได้ column 'name', 'japanese_name', 'abilities'
df[ ['name', 'japanese_name', 'abilities'] ]  # This equals df.loc[ : , ['name', 'japanese_name', 'abilities'] ]

           name     japanese_name                    abilities
0     Bulbasaur  Fushigidaneフシギダネ  ['Overgrow', 'Chlorophyll']
1       Ivysaur   Fushigisouフシギソウ  ['Overgrow', 'Chlorophyll']
2      Venusaur  Fushigibanaフシギバナ  ['Overgrow', 'Chlorophyll']
3    Charmander      Hitokageヒトカゲ     ['Blaze', 'Solar Power']
4    Charmeleon       Lizardoリザード     ['Blaze', 'Solar Power']
..          ...               ...                          ...
796  Celesteela    Tekkaguyaテッカグヤ              ['Beast Boost']
797     Kartana   Kamiturugiカミツルギ              ['Beast Boost']
798    Guzzlord   Akuzikingアクジキング              ['Beast Boost']
799    Necrozma     Necrozmaネクロズマ              ['Prism Armor']
800    Magearna      Magearnaマギアナ               ['Soul-Heart']

[801 rows x 3 columns]

In [32]:
# Select all rows in the range of specified columns (inclusive slicing for label indices)
df.loc[ : , 'hp':'pokedex_number' ]

      hp     japanese_name        name  percentage_male  pokedex_number
0     45  Fushigidaneフシギダネ   Bulbasaur             88.1               1
1     60   Fushigisouフシギソウ     Ivysaur             88.1               2
2     80  Fushigibanaフシギバナ    Venusaur             88.1               3
3     39      Hitokageヒトカゲ  Charmander             88.1               4
4     58       Lizardoリザード  Charmeleon             88.1               5
..   ...               ...         ...              ...             ...
796   97    Tekkaguyaテッカグヤ  Celesteela              NaN             797
797   59   Kamiturugiカミツルギ     Kartana              NaN             798
798  223   Akuzikingアクジキング    Guzzlord              NaN             799
799   97     Necrozmaネクロズマ    Necrozma              NaN             800
800   80      Magearnaマギアナ    Magearna              NaN             801

[801 rows x 5 columns]

In [33]:
df[ 'hp':'pokedex_number' ]   # TypeError

TypeError: cannot do slice indexing on RangeIndex with these indexers [hp] of type str

In short, the short form of `df['col_name']` is less flexible than the explicit indexer of `df.loc[]`.
- Using `df['col_name']` means that all rows must be selected. We cannot choose some rows at will.
- `df['col_name']` doesn't allow slicing.
- `df.loc[]` ensures that the original DataFrame is modified. Continue reading this issue in https://stackoverflow.com/a/48411543.