# 1. IPython.display

**IPython Display** is a tool that allows us to represent our output in many ways beyond the traditional text and numbers. For example, images, HTML, videos, audio, and even interactive widgets.

- Full APIs: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html

# 2. Import library and check version

In [1]:
import sys

print(sys.executable)
print(sys.version)

/workspaces/DADS-5001-Data-Analytics-and-Data-Science-Tools-and-Programming/.venv/bin/python
3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")
print(f"Matplotlib version: {plt.matplotlib.__version__}")

Pandas version: 3.0.5
Numpy version: 2.5.1
Matplotlib version: 3.11.1

In [4]:
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output
print( f"IPython {IPython.__version__}" )

IPython 9.16.1

In [5]:
import pyarrow as pa

print(pa.__version__)

25.0.0

In [6]:
print(sys.executable)

/workspaces/DADS-5001-Data-Analytics-and-Data-Science-Tools-and-Programming/.venv/bin/python

# 3. Pandas: Create data

## 3.1 Create pandas.Series (1D sequence)

In [9]:
# Let pandas figure out a suitable data type for the created Series
sr = pd.Series( [10,20.5,30.6,100,1000] )

# Inspect the data
print( f"type = {type(sr)}" )
print( f"shape = {sr.shape}" )
print( f"dtype = {sr.dtype}\n" )
print( sr )

type = <class 'pandas.Series'>
shape = (5,)
dtype = float64

0      10.0
1      20.5
2      30.6
3     100.0
4    1000.0
dtype: float64

In [10]:
# Specify the data type we want for the created Series
sr = pd.Series( [10,20.5,30.6,100,1000], dtype=np.float32 )
sr

0      10.0
1      20.5
2      30.6
3     100.0
4    1000.0
dtype: float32

In [ ]:
# This command is ok in pandas 1.5.X but produces an error in pandas 2.X
sr = pd.Series( [10,20.5,30.6,100,1000], dtype=np.int32 ) # ValueError
sr

In [13]:
# Create a series with a proper data type to avoid an error
sr1 = pd.Series( [10,20.5,30.6,100,1000], dtype='float64' )   # The default numpy backend
sr2 = pd.Series( [10,20.5,30.6,100,1000], dtype='float64[pyarrow]' )  # The pyarrow backend

# Inspect
display(sr1)
display(sr2)

0      10.0
1      20.5
2      30.6
3     100.0
4    1000.0
dtype: float64

0      10.0
1      20.5
2      30.6
3     100.0
4    1000.0
dtype: double[pyarrow]

In [14]:
# Pandas uses the 'object' dtype for string by default
# The object dtype can store not only string but also mixed data types
sr1 = pd.Series( ['hello', 'good', 'morning', 'teacher' ] )

# Explicitly set the 'string' dtype for the numpy backend
# Note that 'string' is not the same as 'object' (https://stackoverflow.com/questions/34881079/pandas-distinction-between-str-and-object-types)
sr2 = pd.Series( ['hello', 'good', 'morning', 'teacher' ], dtype='string' )

# Explicitly set the 'string' dtype for the pyarrow backend
sr3 = pd.Series( ['hello', 'good', 'morning', 'teacher' ], dtype='string[pyarrow]' )

# Inspect
display(sr1)
display(sr2)
display(sr3)

0      hello
1       good
2    morning
3    teacher
dtype: str

0      hello
1       good
2    morning
3    teacher
dtype: string

0      hello
1       good
2    morning
3    teacher
dtype: string

In [15]:
# Pandas will try it best to fit one suitable dtype to a Series
sr = pd.Series( ['hello', 1, 2, 10.0, True ] )
sr

0    hello
1        1
2        2
3     10.0
4     True
dtype: object

In [16]:
# In pandas with numpy backend, the missing data is varied for different data types
print('==== Numpy ====')
sr1 = pd.Series( [10, 20, 30, None] )
display(sr1)
print( f"The last value of '{sr1.iloc[-1]}' is dtype of '{type(sr1.iloc[-1])}'" )
sr2 = pd.Series( ['car', 'ant', 'zebra', None] )
display(sr2)
print( f"The last value of '{sr2.iloc[-1]}' is dtype of '{type(sr2.iloc[-1])}'" )
sr3 = pd.Series( ['car', 'ant', 'zebra', None], dtype='string' )
display(sr3)
print( f"The last value of '{sr3.iloc[-1]}' is dtype of '{type(sr3.iloc[-1])}'" )

# In pandas with pyarrow backend, there is missing data support (NA) for all data types
print('\n==== PyArrow ====')
sr1 = pd.Series( [10, 20, 30, None], dtype='int64[pyarrow]')
display(sr1)
print( f"The last value of '{sr1.iloc[-1]}' is dtype of '{type(sr1.iloc[-1])}'" )
sr2 = pd.Series( ['car', 'ant', 'zebra', None], dtype='string[pyarrow]' )
display(sr2)
print( f"The last value of '{sr2.iloc[-1]}' is dtype of '{type(sr2.iloc[-1])}'" )

==== Numpy ====

0    10.0
1    20.0
2    30.0
3     NaN
dtype: float64

The last value of 'nan' is dtype of '<class 'numpy.float64'>'

0      car
1      ant
2    zebra
3      NaN
dtype: str

The last value of 'nan' is dtype of '<class 'float'>'

0      car
1      ant
2    zebra
3     <NA>
dtype: string

The last value of '<NA>' is dtype of '<class 'pandas.api.typing.NAType'>'

==== PyArrow ====

0      10
1      20
2      30
3    <NA>
dtype: int64[pyarrow]

The last value of '<NA>' is dtype of '<class 'pandas.api.typing.NAType'>'

0      car
1      ant
2    zebra
3     <NA>
dtype: string

The last value of '<NA>' is dtype of '<class 'pandas.api.typing.NAType'>'

## 3.2 Create pandas.DataFrame (2D sequence)

In [17]:
row0 = [ 'Mary', 50000.00 ]
row1 = [ 'John', 35000 ]
row2 = [ 'George', 25333.33 ]
row3 = [ np.nan, np.nan ]   # np.nan is float that represents missing data
row4 = [ 'Jane', None ]

# Create DataFrame from a list of lists
# Use default indexing for both row and column
df = pd.DataFrame( [ row0, row1, row2, row3, row4 ] )

# Inspect the data
print( f"type = {type(df)}" )
print( f"shape = {df.shape}" )
print( f"row index = {df.index}")
print( f"column index = {df.columns}" )
print( f"\ndtypes:\n{df.dtypes}\n" )
df

type = <class 'pandas.DataFrame'>
shape = (5, 2)
row index = RangeIndex(start=0, stop=5, step=1)
column index = RangeIndex(start=0, stop=2, step=1)

dtypes:
0        str
1    float64
dtype: object

        0         1
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [19]:
# Using print() with 'df' does not produce a nice-looking table
print('----- print(df) -----')
print(df)

# Use the display() command to nicely display the DataFrame
print('\n----- display(df) -----')
display(df)

----- print(df) -----
        0         1
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

----- display(df) -----

        0         1
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [20]:
# Create DataFrame from a list of lists
# Use our own column indices
df = pd.DataFrame( [ row0, row1, row2, row3, row4 ],
                   columns=[111,222] ) # Assigned column indices

print( f"row index = {df.index}")
print( f"column index = {df.columns}" )
df

row index = RangeIndex(start=0, stop=5, step=1)
column index = Index([111, 222], dtype='int64')

      111       222
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [21]:
# Create DataFrame from a list of lists
# Use our own column indices
df = pd.DataFrame( [ row0, row1, row2, row3, row4 ],
                   columns=['Name','Salary'] ) # Assigned column indices

print( f"row index = {df.index}")
print( f"column index = {df.columns}" )
df

row index = RangeIndex(start=0, stop=5, step=1)
column index = Index(['Name', 'Salary'], dtype='str')

     Name    Salary
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [22]:
# Create a DataFrame from a dict of lists
# Dict's keys will become column indices
df = pd.DataFrame( {'Name':['Mary','John','George',np.nan, 'Jane'],
                    'Salary':[50000.00, 35000, 25333.33, np.nan, None] }
                 )
df

     Name    Salary
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [23]:
# It is possible to use our custom row indices
df = pd.DataFrame( {'Name':['Mary','John','George',np.nan, 'Jane'],
                    'Salary':[50000.00, 35000, 25333.33, np.nan, None] },
                    index=['no1','no2','no3','no4', 'no5'] # Assigned row indices
                 )

print( f"row index = {df.index}")
print( f"column index = {df.columns}" )
df

row index = Index(['no1', 'no2', 'no3', 'no4', 'no5'], dtype='str')
column index = Index(['Name', 'Salary'], dtype='str')

       Name    Salary
no1    Mary  50000.00
no2    John  35000.00
no3  George  25333.33
no4     NaN       NaN
no5    Jane       NaN

In [24]:
# Reset row indices to the default 0-based integer values
df.reset_index()    # default: inplace=False, drop=False

  index    Name    Salary
0   no1    Mary  50000.00
1   no2    John  35000.00
2   no3  George  25333.33
3   no4     NaN       NaN
4   no5    Jane       NaN

In [25]:
# Reset row indices to the default and drop the old-index column
df.reset_index(drop=True)

     Name    Salary
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN

In [26]:
# Assign the resultant DataFrame back to the variable
df = df.reset_index(drop=True)  # This equals to df.reset_index(drop=True, inplace=True)
df

     Name    Salary
0    Mary  50000.00
1    John  35000.00
2  George  25333.33
3     NaN       NaN
4    Jane       NaN