In [14]:
import sys
import pandas as pd
import numpy as np
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output

print( f"Python {sys.version}" )
print( f"Pandas {pd.__version__}" )
print( f"NumPy {np.__version__}" )
print( f"IPython {IPython.__version__}" )

Python 3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]
Pandas 3.0.5
NumPy 2.5.1
IPython 9.16.1

# 4. Pandas: Read/Load and inspect a large dataset

## 4.1 Read/Load data from an external data source

Pandas provides many easy-to-use functions to read/load tabular data from CSV, json, excel, SQL database, etc.

<font color=orange>**Tip 1:**</font> If the dataframe is too big to fit on RAM all at once, the memory error will appear. This problem can be solved by processing the data in 'chunk' using the `chunksize` parameter.

<font color=orange>**Tip 2:**</font> Use less memory when loading a large CSV file by specifying `dtype` for each column according to https://www.kaggle.com/code/marcmuc/large-csv-datasets-with-pandas-use-less-memory.

In [15]:
# Read from a CSV file (default delimiter is comma)
# Data type for each column is automatically detected unless otherwise specified.
# Can read from URL on internet and Local Directory as well.
df_pokemon = pd.read_csv('https://raw.githubusercontent.com/ShaileshDhama/Exploratory-Data-Analysis-On-Pokemon-Dataset/master/Complete%20Pokemon.csv')
df_pokemon.shape

(801, 41)

In [16]:
df = df_pokemon
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

## 4.2 Inspect a large dataset

In [17]:
df.head(3)  # Default is to print the first 5 rows

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0

In [18]:
df.tail(10)  # Default is to print the last 5 rows

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
791,['Shadow Shield'],1.00,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,...,NaN,792,137,107,97,psychic,ghost,120.0,7,1
792,['Beast Boost'],0.50,1.0,1.0,1.0,0.5,1.0,0.5,0.5,1.0,...,NaN,793,127,131,103,rock,poison,55.5,7,1
793,['Beast Boost'],0.50,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,NaN,794,53,53,79,bug,fighting,333.6,7,1
794,['Beast Boost'],0.50,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,NaN,795,137,37,151,bug,fighting,25.0,7,1
795,['Beast Boost'],1.00,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,NaN,796,173,71,83,electric,NaN,100.0,7,1
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [19]:
df.sample(4)  # Default is to randomly show one row

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
486,"['Pressure', 'Telepathy', 'Levitate']",0.5,2.0,2.0,0.5,2.0,0.0,0.5,1.0,2.0,...,NaN,487,120,100,90,ghost,dragon,750.0,4,1
362,"['Thick Fat', 'Ice Body', 'Oblivious']",1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,...,50.0,363,55,50,25,ice,water,39.5,3,0
179,"['Static', 'Plus']",1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,50.0,180,80,60,45,electric,NaN,13.3,2,0
622,"['Iron Fist', 'Klutz', 'No Guard']",0.5,2.0,1.0,0.0,1.0,0.0,1.0,1.0,2.0,...,NaN,623,55,80,55,ground,ghost,330.0,5,0

In [20]:
# Inspect available rows and columns in the DataFrame
print( f"{df.index=}\n" )
print( f"{df.columns=}" )

df.index=RangeIndex(start=0, stop=801, step=1)

df.columns=Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='str')

In [21]:
# df.info() is a very convenient way to overview the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), str(7)
memory usage: 325.9 KB

`df.describe()` for concluding the DataFrame with stat
- For numeric data, the result’s index will include count, mean, std, min, max, 25 percentile, 50 percentile (median), and 75 percentile.
- For object data (e.g. strings or timestamps), the result’s index will include count, unique, top (the most common value), and freq (the most common value’s frequency).

In [ ]:
# For mixed data types, the default is to return only an analysis of numeric columns
# Note: df.describe() already skips missing values in the analysis of numeric columns. 
df.describe()   # This equals to df.describe(include=np.number)

,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,...,height_m,hp,percentage_male,pokedex_number,sp_attack,sp_defense,speed,weight_kg,generation,is_legendary
count,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,...,781.000000,801.000000,703.000000,801.000000,801.000000,801.000000,801.000000,781.000000,801.000000,801.000000
mean,0.996255,1.057116,0.968789,1.073970,1.068976,1.065543,1.135456,1.192884,0.985019,1.034020,...,1.163892,68.958801,55.155761,401.000000,71.305868,70.911361,66.334582,61.378105,3.690387,0.087391
std,0.597248,0.438142,0.353058,0.654962,0.522167,0.717251,0.691853,0.604488,0.558256,0.788896,...,1.080326,26.576015,20.261623,231.373075,32.353826,27.942501,28.907662,109.354766,1.930420,0.282583
min,0.250000,0.250000,0.000000,0.000000,0.250000,0.000000,0.250000,0.250000,0.000000,0.250000,...,0.100000,1.000000,0.000000,1.000000,10.000000,20.000000,5.000000,0.100000,1.000000,0.000000
25%,0.500000,1.000000,1.000000,0.500000,1.000000,0.500000,0.500000,1.000000,1.000000,0.500000,...,0.600000,50.000000,50.000000,201.000000,45.000000,50.000000,45.000000,9.000000,2.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,65.000000,50.000000,401.000000,65.000000,66.000000,65.000000,27.300000,4.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,...,1.500000,80.000000,50.000000,601.000000,91.000000,90.000000,85.000000,64.800000,5.000000,0.000000
max,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,14.500000,255.000000,100.000000,801.000000,194.000000,230.000000,180.000000,999.900000,7.000000,1.000000

In [ ]:
# Return a union of attributes of each type
# To include all columns, use df.describe(include='all').
df.describe(include='all')

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
count,801,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,...,703.000000,801.000000,801.000000,801.000000,801.000000,801,417,781.000000,801.000000,801.000000
unique,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18,18,NaN,NaN,NaN
top,['Levitate'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,water,flying,NaN,NaN,NaN
freq,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,114,95,NaN,NaN,NaN
mean,NaN,0.996255,1.057116,0.968789,1.073970,1.068976,1.065543,1.135456,1.192884,0.985019,...,55.155761,401.000000,71.305868,70.911361,66.334582,NaN,NaN,61.378105,3.690387,0.087391
std,NaN,0.597248,0.438142,0.353058,0.654962,0.522167,0.717251,0.691853,0.604488,0.558256,...,20.261623,231.373075,32.353826,27.942501,28.907662,NaN,NaN,109.354766,1.930420,0.282583
min,NaN,0.250000,0.250000,0.000000,0.000000,0.250000,0.000000,0.250000,0.250000,0.000000,...,0.000000,1.000000,10.000000,20.000000,5.000000,NaN,NaN,0.100000,1.000000,0.000000
25%,NaN,0.500000,1.000000,1.000000,0.500000,1.000000,0.500000,0.500000,1.000000,1.000000,...,50.000000,201.000000,45.000000,50.000000,45.000000,NaN,NaN,9.000000,2.000000,0.000000
50%,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,50.000000,401.000000,65.000000,66.000000,65.000000,NaN,NaN,27.300000,4.000000,0.000000
75%,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,50.000000,601.000000,91.000000,90.000000,85.000000,NaN,NaN,64.800000,5.000000,0.000000
max,NaN,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,100.000000,801.000000,194.000000,230.000000,180.000000,NaN,NaN,999.900000,7.000000,1.000000

In [24]:
# Limit results to object columns
df.describe(include=object)

/tmp/ipykernel_9976/146469349.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,abilities,capture_rate,classfication,japanese_name,name,type1,type2
count,801,801,801,801,801,801,417
unique,482,34,588,801,801,18,18
top,['Levitate'],45,Dragon Pokémon,Fushigidaneフシギダネ,Bulbasaur,water,flying
freq,29,250,8,1,1,114,95

In [25]:
# Limit results to object and int64 columns
df.describe(include=[object, np.int64])

/tmp/ipykernel_9976/248600987.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=[object, np.int64])

,abilities,attack,base_egg_steps,base_happiness,base_total,capture_rate,classfication,defense,experience_growth,hp,japanese_name,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,generation,is_legendary
count,801,801.000000,801.000000,801.000000,801.000000,801,801,801.000000,8.010000e+02,801.000000,801,801,801.000000,801.000000,801.000000,801.000000,801,417,801.000000,801.000000
unique,482,NaN,NaN,NaN,NaN,34,588,NaN,NaN,NaN,801,801,NaN,NaN,NaN,NaN,18,18,NaN,NaN
top,['Levitate'],NaN,NaN,NaN,NaN,45,Dragon Pokémon,NaN,NaN,NaN,Fushigidaneフシギダネ,Bulbasaur,NaN,NaN,NaN,NaN,water,flying,NaN,NaN
freq,29,NaN,NaN,NaN,NaN,250,8,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,114,95,NaN,NaN
mean,NaN,77.857678,7191.011236,65.362047,428.377029,NaN,NaN,73.008739,1.054996e+06,68.958801,NaN,NaN,401.000000,71.305868,70.911361,66.334582,NaN,NaN,3.690387,0.087391
std,NaN,32.158820,6558.220422,19.598948,119.203577,NaN,NaN,30.769159,1.602558e+05,26.576015,NaN,NaN,231.373075,32.353826,27.942501,28.907662,NaN,NaN,1.930420,0.282583
min,NaN,5.000000,1280.000000,0.000000,180.000000,NaN,NaN,5.000000,6.000000e+05,1.000000,NaN,NaN,1.000000,10.000000,20.000000,5.000000,NaN,NaN,1.000000,0.000000
25%,NaN,55.000000,5120.000000,70.000000,320.000000,NaN,NaN,50.000000,1.000000e+06,50.000000,NaN,NaN,201.000000,45.000000,50.000000,45.000000,NaN,NaN,2.000000,0.000000
50%,NaN,75.000000,5120.000000,70.000000,435.000000,NaN,NaN,70.000000,1.000000e+06,65.000000,NaN,NaN,401.000000,65.000000,66.000000,65.000000,NaN,NaN,4.000000,0.000000
75%,NaN,100.000000,6400.000000,70.000000,505.000000,NaN,NaN,90.000000,1.059860e+06,80.000000,NaN,NaN,601.000000,91.000000,90.000000,85.000000,NaN,NaN,5.000000,0.000000
max,NaN,185.000000,30720.000000,140.000000,780.000000,NaN,NaN,230.000000,1.640000e+06,255.000000,NaN,NaN,801.000000,194.000000,230.000000,180.000000,NaN,NaN,7.000000,1.000000

In [26]:
# Limit results to non-float64 columns
df.describe(exclude='float64')

,abilities,attack,base_egg_steps,base_happiness,base_total,capture_rate,classfication,defense,experience_growth,hp,japanese_name,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,generation,is_legendary
count,801,801.000000,801.000000,801.000000,801.000000,801,801,801.000000,8.010000e+02,801.000000,801,801,801.000000,801.000000,801.000000,801.000000,801,417,801.000000,801.000000
unique,482,NaN,NaN,NaN,NaN,34,588,NaN,NaN,NaN,801,801,NaN,NaN,NaN,NaN,18,18,NaN,NaN
top,['Levitate'],NaN,NaN,NaN,NaN,45,Dragon Pokémon,NaN,NaN,NaN,Fushigidaneフシギダネ,Bulbasaur,NaN,NaN,NaN,NaN,water,flying,NaN,NaN
freq,29,NaN,NaN,NaN,NaN,250,8,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,114,95,NaN,NaN
mean,NaN,77.857678,7191.011236,65.362047,428.377029,NaN,NaN,73.008739,1.054996e+06,68.958801,NaN,NaN,401.000000,71.305868,70.911361,66.334582,NaN,NaN,3.690387,0.087391
std,NaN,32.158820,6558.220422,19.598948,119.203577,NaN,NaN,30.769159,1.602558e+05,26.576015,NaN,NaN,231.373075,32.353826,27.942501,28.907662,NaN,NaN,1.930420,0.282583
min,NaN,5.000000,1280.000000,0.000000,180.000000,NaN,NaN,5.000000,6.000000e+05,1.000000,NaN,NaN,1.000000,10.000000,20.000000,5.000000,NaN,NaN,1.000000,0.000000
25%,NaN,55.000000,5120.000000,70.000000,320.000000,NaN,NaN,50.000000,1.000000e+06,50.000000,NaN,NaN,201.000000,45.000000,50.000000,45.000000,NaN,NaN,2.000000,0.000000
50%,NaN,75.000000,5120.000000,70.000000,435.000000,NaN,NaN,70.000000,1.000000e+06,65.000000,NaN,NaN,401.000000,65.000000,66.000000,65.000000,NaN,NaN,4.000000,0.000000
75%,NaN,100.000000,6400.000000,70.000000,505.000000,NaN,NaN,90.000000,1.059860e+06,80.000000,NaN,NaN,601.000000,91.000000,90.000000,85.000000,NaN,NaN,5.000000,0.000000
max,NaN,185.000000,30720.000000,140.000000,780.000000,NaN,NaN,230.000000,1.640000e+06,255.000000,NaN,NaN,801.000000,194.000000,230.000000,180.000000,NaN,NaN,7.000000,1.000000