In [1]:
import sys
import pandas as pd
import numpy as np
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output

print( f"Python {sys.version}" )
print( f"Pandas {pd.__version__}" )
print( f"NumPy {np.__version__}" )
print( f"IPython {IPython.__version__}" )

Python 3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]
Pandas 3.0.5
NumPy 2.5.1
IPython 9.16.1

In [2]:
# Read from a CSV file (default delimiter is comma)
# Data type for each column is automatically detected unless otherwise specified.
# Can read from URL on internet and Local Directory as well.
df_pokemon = pd.read_csv('https://raw.githubusercontent.com/ShaileshDhama/Exploratory-Data-Analysis-On-Pokemon-Dataset/master/Complete%20Pokemon.csv')
df_pokemon.shape
df = df_pokemon

# 5. Pandas: Make changes to the data

In [3]:
# Preview the dataset (just a reminder)
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [4]:
# Rename existing columns
df2 = df.rename(columns={'abilities':'skill', 'pokedex_number':'pokedex_no'}) # default: inplace=False
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   skill              801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_no         801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), str(7)
memory usage: 325.9 KB

In [5]:
# Set an existing column as the row index
# This is convenient for visualization commands that use row index as their default values for x-axis

df2 = df.set_index('name')    # default: inplace=False
df2.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
name,,,,,,,,,,,,,,,,,,,,,
Bulbasaur,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
Ivysaur,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
Venusaur,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
Charmander,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
Charmeleon,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [6]:
# In pandas, many operations are vectorized, making them more optimized and faster than  writing a loop ourselves
# Also, automatic broadcasting is performed underneath to match shapes of data

# Explanation
# 1. Add two pandas.Series in an element-wise manner
# 2. Divide the resultant pandas.Series with a scalar of 2 (element-wise division with automatic broadcasting)
# 3. Assign the resultant pandas.Series to the selected column; create the new column if the specified column name does not exist
df['dummy'] = ( df['against_bug'] + df['against_dark'] ) / 2

# Inspect the resultant pandas.DataFrame
df.info()

# Validate values in the newly created column
df.loc[ : , ['against_bug', 'against_dark', 'dummy'] ]

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
 41  dummy              801 non-null    float64
dtypes: float64(22), int64(13), str(7)
memory usage: 332.2 KB

     against_bug  against_dark  dummy
0           1.00           1.0  1.000
1           1.00           1.0  1.000
2           1.00           1.0  1.000
3           0.50           1.0  0.750
4           0.50           1.0  0.750
..           ...           ...    ...
796         0.25           1.0  0.625
797         1.00           1.0  1.000
798         2.00           0.5  1.250
799         2.00           2.0  2.000
800         0.25           0.5  0.375

[801 rows x 3 columns]

In [ ]:
# Add a new row to pandas.DataFrame by specifying row index that does not exist

# ถ้า access row ที่ไม่มีใน data set จะมีการสร้าง row ใหม่ขึ้นมาโดยอัตโนมัติ และค่าของ column ที่ไม่ได้ระบุจะถูกกำหนดเป็น NaN
# หลักการเหมือน dictionay

# Add a new row
df.loc[ 1000 ] = pd.NA   # This equals df.loc[1000] = np.nan

# Inspect the result
print( f"{df.index=}" )
df.tail()

df.index=Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
        792,  793,  794,  795,  796,  797,  798,  799,  800, 1000],
      dtype='int64', length=802)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,dummy
797,['Beast Boost'],1.0,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,798,59,31,109,grass,steel,0.1,7,1,1.0
798,['Beast Boost'],2.0,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,799,97,53,43,dark,dragon,888.0,7,1,1.25
799,['Prism Armor'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,800,127,89,79,psychic,NaN,230.0,7,1,2.0
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,801,130,115,65,steel,fairy,80.5,7,1,0.375
1000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [9]:
# Drop rows by slicing

# Drop three rows at the top
df = df.iloc[ 3: ]
display( df.head() )

# Drop three rows at the bottom
df = df.iloc[ :-3 ]
display( df.tail() )

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,dummy
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,7,50,64,43,water,NaN,9.0,1,0,1.0
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,8,65,80,58,water,NaN,22.5,1,0,1.0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,9,135,115,78,water,NaN,85.5,1,0,1.0
9,"['Shield Dust', 'Run Away']",1.0,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,...,10,20,20,45,bug,NaN,2.9,1,0,1.0
10,['Shed Skin'],1.0,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,...,11,25,25,30,bug,NaN,9.9,1,0,1.0

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,dummy
791,['Shadow Shield'],1.0,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,...,792,137,107,97,psychic,ghost,120.0,7,1,2.5
792,['Beast Boost'],0.5,1.0,1.0,1.0,0.5,1.0,0.5,0.5,1.0,...,793,127,131,103,rock,poison,55.5,7,1,0.75
793,['Beast Boost'],0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,794,53,53,79,bug,fighting,333.6,7,1,0.5
794,['Beast Boost'],0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,795,137,37,151,bug,fighting,25.0,7,1,0.5
795,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,796,173,71,83,electric,NaN,100.0,7,1,1.0

In [10]:
# Drop columns by df.drop()
df = df.drop( columns=['dummy'] )  # This equals df.drop(columns=['dummy'], inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 790 entries, 6 to 795
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          790 non-null    object
 1   against_bug        790 non-null    object
 2   against_dark       790 non-null    object
 3   against_dragon     790 non-null    object
 4   against_electric   790 non-null    object
 5   against_fairy      790 non-null    object
 6   against_fight      790 non-null    object
 7   against_fire       790 non-null    object
 8   against_flying     790 non-null    object
 9   against_ghost      790 non-null    object
 10  against_grass      790 non-null    object
 11  against_ground     790 non-null    object
 12  against_ice        790 non-null    object
 13  against_normal     790 non-null    object
 14  against_poison     790 non-null    object
 15  against_psychic    790 non-null    object
 16  against_rock       790 non-null    object
 17  against_steel      790 non-null    object
 18  against_water      790 non-null    object
 19  attack             790 non-null    object
 20  base_egg_steps     790 non-null    object
 21  base_happiness     790 non-null    object
 22  base_total         790 non-null    object
 23  capture_rate       790 non-null    object
 24  classfication      790 non-null    object
 25  defense            790 non-null    object
 26  experience_growth  790 non-null    object
 27  height_m           770 non-null    object
 28  hp                 790 non-null    object
 29  japanese_name      790 non-null    object
 30  name               790 non-null    object
 31  percentage_male    697 non-null    object
 32  pokedex_number     790 non-null    object
 33  sp_attack          790 non-null    object
 34  sp_defense         790 non-null    object
 35  speed              790 non-null    object
 36  type1              790 non-null    object
 37  type2              409 non-null    object
 38  weight_kg          770 non-null    object
 39  generation         790 non-null    object
 40  is_legendary       790 non-null    object
dtypes: object(41)
memory usage: 259.2+ KB

In [11]:
# Drop rows by df.drop()
df = df.drop( index=df.index[3:6] )  # This equals df.drop( index=[3,4,5] )

print( df.index )
df.head(15)

Index([  6,   7,   8,  12,  13,  14,  15,  16,  17,  18,
       ...
       786, 787, 788, 789, 790, 791, 792, 793, 794, 795],
      dtype='int64', length=787)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
12,"['Shield Dust', 'Run Away']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,13,20,20,50,bug,poison,3.2,1,0
13,['Shed Skin'],0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,14,25,25,35,bug,poison,10.0,1,0
14,"['Swarm', 'Sniper']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,15,15,80,145,bug,poison,29.5,1,0
15,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,16,35,35,56,normal,flying,1.8,1,0
16,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,17,50,50,71,normal,flying,30.0,1,0
17,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,18,135,80,121,normal,flying,39.5,1,0
18,"['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hu...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,19,25,35,72,normal,dark,NaN,1,0
19,"['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hu...",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,50.0,20,40,80,77,normal,dark,NaN,1,0
20,"['Keen Eye', 'Sniper']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,21,31,31,70,normal,flying,2.0,1,0
21,"['Keen Eye', 'Sniper']",0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,...,50.0,22,61,61,100,normal,flying,38.0,1,0
22,"['Intimidate', 'Shed Skin', 'Unnerve']",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,23,40,54,55,poison,NaN,6.9,1,0
23,"['Intimidate', 'Shed Skin', 'Unnerve']",0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,...,50.0,24,65,79,80,poison,NaN,65.0,1,0

In [12]:
# Once in a while, reset row indices back to 0 ~ (N-1)
df.reset_index(drop=True, inplace=True)
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
1,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
2,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
3,"['Shield Dust', 'Run Away']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,13,20,20,50,bug,poison,3.2,1,0
4,['Shed Skin'],0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,14,25,25,35,bug,poison,10.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782,['Shadow Shield'],1.0,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,...,NaN,792,137,107,97,psychic,ghost,120.0,7,1
783,['Beast Boost'],0.5,1.0,1.0,1.0,0.5,1.0,0.5,0.5,1.0,...,NaN,793,127,131,103,rock,poison,55.5,7,1
784,['Beast Boost'],0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,NaN,794,53,53,79,bug,fighting,333.6,7,1
785,['Beast Boost'],0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,NaN,795,137,37,151,bug,fighting,25.0,7,1
786,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,NaN,796,173,71,83,electric,NaN,100.0,7,1