In [1]:
import sys
import pandas as pd
import numpy as np
import IPython
from IPython.display import display, Markdown, Latex, HTML, IFrame, JSON, Code, Image, YouTubeVideo, clear_output

print( f"Python {sys.version}" )
print( f"Pandas {pd.__version__}" )
print( f"NumPy {np.__version__}" )
print( f"IPython {IPython.__version__}" )

Python 3.13.14 (main, Jul 14 2026, 04:45:36) [GCC 14.2.0]
Pandas 3.0.5
NumPy 2.5.1
IPython 9.16.1

In [2]:
# Read from a CSV file (default delimiter is comma)
# Data type for each column is automatically detected unless otherwise specified.
# Can read from URL on internet and Local Directory as well.
df_pokemon = pd.read_csv('https://raw.githubusercontent.com/ShaileshDhama/Exploratory-Data-Analysis-On-Pokemon-Dataset/master/Complete%20Pokemon.csv')
df_pokemon.shape
df = df_pokemon

# 7. Pandas: Save/Render the output data

In [5]:
# Save as a text-only CSV file
df.to_csv('pokemon_subset.csv')

In [6]:
# Save as an Excel file (including table styling, if any)
# To style the pandas' table, wait for the "Table visualization" section in Pandas4.ipynb
import openpyxl
df.to_excel('pokemon_subset.xlsx')

In [7]:
# Render the DataFrame to HTML codes
# Display HTML results with IPython.display

# Render
render = df.head().to_html()   # As a demo, here we show only the first 5 rows
print(f"{type(render)=}\n\nValue:\n{render}\n")

# Display
print('Display:\n')
display( HTML(render))

type(render)=<class 'str'>

Value:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>abilities</th>
      <th>against_bug</th>
      <th>against_dark</th>
      <th>against_dragon</th>
      <th>against_electric</th>
      <th>against_fairy</th>
      <th>against_fight</th>
      <th>against_fire</th>
      <th>against_flying</th>
      <th>against_ghost</th>
      <th>against_grass</th>
      <th>against_ground</th>
      <th>against_ice</th>
      <th>against_normal</th>
      <th>against_poison</th>
      <th>against_psychic</th>
      <th>against_rock</th>
      <th>against_steel</th>
      <th>against_water</th>
      <th>attack</th>
      <th>base_egg_steps</th>
      <th>base_happiness</th>
      <th>base_total</th>
      <th>capture_rate</th>
      <th>classfication</th>
      <th>defense</th>
      <th>experience_growth</th>
      <th>height_m</th>
      <th>hp</th>
      <th>japanese_name</th>
      <th>name</th>
      <th>percentage_male</th>
      <th>pokedex_number</th>
      <th>sp_attack</th>
      <th>sp_defense</th>
      <th>speed</th>
      <th>type1</th>
      <th>type2</th>
      <th>weight_kg</th>
      <th>generation</th>
      <th>is_legendary</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>['Overgrow', 'Chlorophyll']</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.25</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>49</td>
      <td>5120</td>
      <td>70</td>
      <td>318</td>
      <td>45</td>
      <td>Seed Pokémon</td>
      <td>49</td>
      <td>1059860</td>
      <td>0.7</td>
      <td>45</td>
      <td>Fushigidaneフシギダネ</td>
      <td>Bulbasaur</td>
      <td>88.1</td>
      <td>1</td>
      <td>65</td>
      <td>65</td>
      <td>45</td>
      <td>grass</td>
      <td>poison</td>
      <td>6.9</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>['Overgrow', 'Chlorophyll']</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.25</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>62</td>
      <td>5120</td>
      <td>70</td>
      <td>405</td>
      <td>45</td>
      <td>Seed Pokémon</td>
      <td>63</td>
      <td>1059860</td>
      <td>1.0</td>
      <td>60</td>
      <td>Fushigisouフシギソウ</td>
      <td>Ivysaur</td>
      <td>88.1</td>
      <td>2</td>
      <td>80</td>
      <td>80</td>
      <td>60</td>
      <td>grass</td>
      <td>poison</td>
      <td>13.0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>['Overgrow', 'Chlorophyll']</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.25</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>100</td>
      <td>5120</td>
      <td>70</td>
      <td>625</td>
      <td>45</td>
      <td>Seed Pokémon</td>
      <td>123</td>
      <td>1059860</td>
      <td>2.0</td>
      <td>80</td>
      <td>Fushigibanaフシギバナ</td>
      <td>Venusaur</td>
      <td>88.1</td>
      <td>3</td>
      <td>122</td>
      <td>120</td>
      <td>80</td>
      <td>grass</td>
      <td>poison</td>
      <td>100.0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>['Blaze', 'Solar Power']</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.50</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>2.0</td>
      <td>52</td>
      <td>5120</td>
      <td>70</td>
      <td>309</td>
      <td>45</td>
      <td>Lizard Pokémon</td>
      <td>43</td>
      <td>1059860</td>
      <td>0.6</td>
      <td>39</td>
      <td>Hitokageヒトカゲ</td>
      <td>Charmander</td>
      <td>88.1</td>
      <td>4</td>
      <td>60</td>
      <td>50</td>
      <td>65</td>
      <td>fire</td>
      <td>NaN</td>
      <td>8.5</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>['Blaze', 'Solar Power']</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.50</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>2.0</td>
      <td>64</td>
      <td>5120</td>
      <td>70</td>
      <td>405</td>
      <td>45</td>
      <td>Flame Pokémon</td>
      <td>58</td>
      <td>1059860</td>
      <td>1.1</td>
      <td>58</td>
      <td>Lizardoリザード</td>
      <td>Charmeleon</td>
      <td>88.1</td>
      <td>5</td>
      <td>80</td>
      <td>65</td>
      <td>80</td>
      <td>fire</td>
      <td>NaN</td>
      <td>19.0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

Display:

In [9]:
# Render the DataFrame to latex codes
# Display Latex results with IPython.display
import jinja2
# Render
render = df.head().to_latex()   # As a demo, here we show only the first 5 rows
print(f"{type(render)=}\n\nValue:\n{render}\n")

# Display
# Unfortunately, the Latex() module in IPython.display is intended for showing math equations, not table visualization
print('Display:\n')
display( Latex(render))

type(render)=<class 'str'>

Value:
\begin{tabular}{llrrrrrrrrrrrrrrrrrrrrrrllrrrrllrrrrrllrrr}
\toprule
 & abilities & against_bug & against_dark & against_dragon & against_electric & against_fairy & against_fight & against_fire & against_flying & against_ghost & against_grass & against_ground & against_ice & against_normal & against_poison & against_psychic & against_rock & against_steel & against_water & attack & base_egg_steps & base_happiness & base_total & capture_rate & classfication & defense & experience_growth & height_m & hp & japanese_name & name & percentage_male & pokedex_number & sp_attack & sp_defense & speed & type1 & type2 & weight_kg & generation & is_legendary \\
\midrule
0 & ['Overgrow', 'Chlorophyll'] & 1.000000 & 1.000000 & 1.000000 & 0.500000 & 0.500000 & 0.500000 & 2.000000 & 2.000000 & 1.000000 & 0.250000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 0.500000 & 49 & 5120 & 70 & 318 & 45 & Seed Pokémon & 49 & 1059860 & 0.700000 & 45 & Fushigidaneフシギダネ & Bulbasaur & 88.100000 & 1 & 65 & 65 & 45 & grass & poison & 6.900000 & 1 & 0 \\
1 & ['Overgrow', 'Chlorophyll'] & 1.000000 & 1.000000 & 1.000000 & 0.500000 & 0.500000 & 0.500000 & 2.000000 & 2.000000 & 1.000000 & 0.250000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 0.500000 & 62 & 5120 & 70 & 405 & 45 & Seed Pokémon & 63 & 1059860 & 1.000000 & 60 & Fushigisouフシギソウ & Ivysaur & 88.100000 & 2 & 80 & 80 & 60 & grass & poison & 13.000000 & 1 & 0 \\
2 & ['Overgrow', 'Chlorophyll'] & 1.000000 & 1.000000 & 1.000000 & 0.500000 & 0.500000 & 0.500000 & 2.000000 & 2.000000 & 1.000000 & 0.250000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 2.000000 & 1.000000 & 1.000000 & 0.500000 & 100 & 5120 & 70 & 625 & 45 & Seed Pokémon & 123 & 1059860 & 2.000000 & 80 & Fushigibanaフシギバナ & Venusaur & 88.100000 & 3 & 122 & 120 & 80 & grass & poison & 100.000000 & 1 & 0 \\
3 & ['Blaze', 'Solar Power'] & 0.500000 & 1.000000 & 1.000000 & 1.000000 & 0.500000 & 1.000000 & 0.500000 & 1.000000 & 1.000000 & 0.500000 & 2.000000 & 0.500000 & 1.000000 & 1.000000 & 1.000000 & 2.000000 & 0.500000 & 2.000000 & 52 & 5120 & 70 & 309 & 45 & Lizard Pokémon & 43 & 1059860 & 0.600000 & 39 & Hitokageヒトカゲ & Charmander & 88.100000 & 4 & 60 & 50 & 65 & fire & NaN & 8.500000 & 1 & 0 \\
4 & ['Blaze', 'Solar Power'] & 0.500000 & 1.000000 & 1.000000 & 1.000000 & 0.500000 & 1.000000 & 0.500000 & 1.000000 & 1.000000 & 0.500000 & 2.000000 & 0.500000 & 1.000000 & 1.000000 & 1.000000 & 2.000000 & 0.500000 & 2.000000 & 64 & 5120 & 70 & 405 & 45 & Flame Pokémon & 58 & 1059860 & 1.100000 & 58 & Lizardoリザード & Charmeleon & 88.100000 & 5 & 80 & 65 & 80 & fire & NaN & 19.000000 & 1 & 0 \\
\bottomrule
\end{tabular}


Display:

In [10]:
# Render the DataFrame to JSON codes
# Display JSON results with the "json" module

# Render
render = df.head().to_json()   # As a demo, here we show only the first 5 rows
print(f"{type(render)=}\nValue:\n{render}\n")  # 'render' is now a JSON string

# Convert from JSON string to JSON object
import json
json_obj = json.loads(render)
print(f"{type(json_obj)=}\nValue:\n{json_obj}\n")  # 'json_obj' is now a JSON object

# Display
print('Display:')
print( json.dumps(json_obj, indent=2) )

type(render)=<class 'str'>
Value:
{"abilities":{"0":"['Overgrow', 'Chlorophyll']","1":"['Overgrow', 'Chlorophyll']","2":"['Overgrow', 'Chlorophyll']","3":"['Blaze', 'Solar Power']","4":"['Blaze', 'Solar Power']"},"against_bug":{"0":1.0,"1":1.0,"2":1.0,"3":0.5,"4":0.5},"against_dark":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_dragon":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_electric":{"0":0.5,"1":0.5,"2":0.5,"3":1.0,"4":1.0},"against_fairy":{"0":0.5,"1":0.5,"2":0.5,"3":0.5,"4":0.5},"against_fight":{"0":0.5,"1":0.5,"2":0.5,"3":1.0,"4":1.0},"against_fire":{"0":2.0,"1":2.0,"2":2.0,"3":0.5,"4":0.5},"against_flying":{"0":2.0,"1":2.0,"2":2.0,"3":1.0,"4":1.0},"against_ghost":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_grass":{"0":0.25,"1":0.25,"2":0.25,"3":0.5,"4":0.5},"against_ground":{"0":1.0,"1":1.0,"2":1.0,"3":2.0,"4":2.0},"against_ice":{"0":2.0,"1":2.0,"2":2.0,"3":0.5,"4":0.5},"against_normal":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_poison":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_psychic":{"0":2.0,"1":2.0,"2":2.0,"3":1.0,"4":1.0},"against_rock":{"0":1.0,"1":1.0,"2":1.0,"3":2.0,"4":2.0},"against_steel":{"0":1.0,"1":1.0,"2":1.0,"3":0.5,"4":0.5},"against_water":{"0":0.5,"1":0.5,"2":0.5,"3":2.0,"4":2.0},"attack":{"0":49,"1":62,"2":100,"3":52,"4":64},"base_egg_steps":{"0":5120,"1":5120,"2":5120,"3":5120,"4":5120},"base_happiness":{"0":70,"1":70,"2":70,"3":70,"4":70},"base_total":{"0":318,"1":405,"2":625,"3":309,"4":405},"capture_rate":{"0":"45","1":"45","2":"45","3":"45","4":"45"},"classfication":{"0":"Seed Pok\u00e9mon","1":"Seed Pok\u00e9mon","2":"Seed Pok\u00e9mon","3":"Lizard Pok\u00e9mon","4":"Flame Pok\u00e9mon"},"defense":{"0":49,"1":63,"2":123,"3":43,"4":58},"experience_growth":{"0":1059860,"1":1059860,"2":1059860,"3":1059860,"4":1059860},"height_m":{"0":0.7,"1":1.0,"2":2.0,"3":0.6,"4":1.1},"hp":{"0":45,"1":60,"2":80,"3":39,"4":58},"japanese_name":{"0":"Fushigidane\u30d5\u30b7\u30ae\u30c0\u30cd","1":"Fushigisou\u30d5\u30b7\u30ae\u30bd\u30a6","2":"Fushigibana\u30d5\u30b7\u30ae\u30d0\u30ca","3":"Hitokage\u30d2\u30c8\u30ab\u30b2","4":"Lizardo\u30ea\u30b6\u30fc\u30c9"},"name":{"0":"Bulbasaur","1":"Ivysaur","2":"Venusaur","3":"Charmander","4":"Charmeleon"},"percentage_male":{"0":88.1,"1":88.1,"2":88.1,"3":88.1,"4":88.1},"pokedex_number":{"0":1,"1":2,"2":3,"3":4,"4":5},"sp_attack":{"0":65,"1":80,"2":122,"3":60,"4":80},"sp_defense":{"0":65,"1":80,"2":120,"3":50,"4":65},"speed":{"0":45,"1":60,"2":80,"3":65,"4":80},"type1":{"0":"grass","1":"grass","2":"grass","3":"fire","4":"fire"},"type2":{"0":"poison","1":"poison","2":"poison","3":null,"4":null},"weight_kg":{"0":6.9,"1":13.0,"2":100.0,"3":8.5,"4":19.0},"generation":{"0":1,"1":1,"2":1,"3":1,"4":1},"is_legendary":{"0":0,"1":0,"2":0,"3":0,"4":0}}

type(json_obj)=<class 'dict'>
Value:
{'abilities': {'0': "['Overgrow', 'Chlorophyll']", '1': "['Overgrow', 'Chlorophyll']", '2': "['Overgrow', 'Chlorophyll']", '3': "['Blaze', 'Solar Power']", '4': "['Blaze', 'Solar Power']"}, 'against_bug': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 0.5, '4': 0.5}, 'against_dark': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_dragon': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_electric': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 1.0, '4': 1.0}, 'against_fairy': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 0.5, '4': 0.5}, 'against_fight': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 1.0, '4': 1.0}, 'against_fire': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 0.5, '4': 0.5}, 'against_flying': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 1.0, '4': 1.0}, 'against_ghost': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_grass': {'0': 0.25, '1': 0.25, '2': 0.25, '3': 0.5, '4': 0.5}, 'against_ground': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 2.0, '4': 2.0}, 'against_ice': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 0.5, '4': 0.5}, 'against_normal': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_poison': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_psychic': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 1.0, '4': 1.0}, 'against_rock': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 2.0, '4': 2.0}, 'against_steel': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 0.5, '4': 0.5}, 'against_water': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 2.0, '4': 2.0}, 'attack': {'0': 49, '1': 62, '2': 100, '3': 52, '4': 64}, 'base_egg_steps': {'0': 5120, '1': 5120, '2': 5120, '3': 5120, '4': 5120}, 'base_happiness': {'0': 70, '1': 70, '2': 70, '3': 70, '4': 70}, 'base_total': {'0': 318, '1': 405, '2': 625, '3': 309, '4': 405}, 'capture_rate': {'0': '45', '1': '45', '2': '45', '3': '45', '4': '45'}, 'classfication': {'0': 'Seed Pokémon', '1': 'Seed Pokémon', '2': 'Seed Pokémon', '3': 'Lizard Pokémon', '4': 'Flame Pokémon'}, 'defense': {'0': 49, '1': 63, '2': 123, '3': 43, '4': 58}, 'experience_growth': {'0': 1059860, '1': 1059860, '2': 1059860, '3': 1059860, '4': 1059860}, 'height_m': {'0': 0.7, '1': 1.0, '2': 2.0, '3': 0.6, '4': 1.1}, 'hp': {'0': 45, '1': 60, '2': 80, '3': 39, '4': 58}, 'japanese_name': {'0': 'Fushigidaneフシギダネ', '1': 'Fushigisouフシギソウ', '2': 'Fushigibanaフシギバナ', '3': 'Hitokageヒトカゲ', '4': 'Lizardoリザード'}, 'name': {'0': 'Bulbasaur', '1': 'Ivysaur', '2': 'Venusaur', '3': 'Charmander', '4': 'Charmeleon'}, 'percentage_male': {'0': 88.1, '1': 88.1, '2': 88.1, '3': 88.1, '4': 88.1}, 'pokedex_number': {'0': 1, '1': 2, '2': 3, '3': 4, '4': 5}, 'sp_attack': {'0': 65, '1': 80, '2': 122, '3': 60, '4': 80}, 'sp_defense': {'0': 65, '1': 80, '2': 120, '3': 50, '4': 65}, 'speed': {'0': 45, '1': 60, '2': 80, '3': 65, '4': 80}, 'type1': {'0': 'grass', '1': 'grass', '2': 'grass', '3': 'fire', '4': 'fire'}, 'type2': {'0': 'poison', '1': 'poison', '2': 'poison', '3': None, '4': None}, 'weight_kg': {'0': 6.9, '1': 13.0, '2': 100.0, '3': 8.5, '4': 19.0}, 'generation': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}, 'is_legendary': {'0': 0, '1': 0, '2': 0, '3': 0, '4': 0}}

Display:
{
  "abilities": {
    "0": "['Overgrow', 'Chlorophyll']",
    "1": "['Overgrow', 'Chlorophyll']",
    "2": "['Overgrow', 'Chlorophyll']",
    "3": "['Blaze', 'Solar Power']",
    "4": "['Blaze', 'Solar Power']"
  },
  "against_bug": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 0.5,
    "4": 0.5
  },
  "against_dark": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_dragon": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_electric": {
    "0": 0.5,
    "1": 0.5,
    "2": 0.5,
    "3": 1.0,
    "4": 1.0
  },
  "against_fairy": {
    "0": 0.5,
    "1": 0.5,
    "2": 0.5,
    "3": 0.5,
    "4": 0.5
  },
  "against_fight": {
    "0": 0.5,
    "1": 0.5,
    "2": 0.5,
    "3": 1.0,
    "4": 1.0
  },
  "against_fire": {
    "0": 2.0,
    "1": 2.0,
    "2": 2.0,
    "3": 0.5,
    "4": 0.5
  },
  "against_flying": {
    "0": 2.0,
    "1": 2.0,
    "2": 2.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_ghost": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_grass": {
    "0": 0.25,
    "1": 0.25,
    "2": 0.25,
    "3": 0.5,
    "4": 0.5
  },
  "against_ground": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 2.0,
    "4": 2.0
  },
  "against_ice": {
    "0": 2.0,
    "1": 2.0,
    "2": 2.0,
    "3": 0.5,
    "4": 0.5
  },
  "against_normal": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_poison": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_psychic": {
    "0": 2.0,
    "1": 2.0,
    "2": 2.0,
    "3": 1.0,
    "4": 1.0
  },
  "against_rock": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 2.0,
    "4": 2.0
  },
  "against_steel": {
    "0": 1.0,
    "1": 1.0,
    "2": 1.0,
    "3": 0.5,
    "4": 0.5
  },
  "against_water": {
    "0": 0.5,
    "1": 0.5,
    "2": 0.5,
    "3": 2.0,
    "4": 2.0
  },
  "attack": {
    "0": 49,
    "1": 62,
    "2": 100,
    "3": 52,
    "4": 64
  },
  "base_egg_steps": {
    "0": 5120,
    "1": 5120,
    "2": 5120,
    "3": 5120,
    "4": 5120
  },
  "base_happiness": {
    "0": 70,
    "1": 70,
    "2": 70,
    "3": 70,
    "4": 70
  },
  "base_total": {
    "0": 318,
    "1": 405,
    "2": 625,
    "3": 309,
    "4": 405
  },
  "capture_rate": {
    "0": "45",
    "1": "45",
    "2": "45",
    "3": "45",
    "4": "45"
  },
  "classfication": {
    "0": "Seed Pok\u00e9mon",
    "1": "Seed Pok\u00e9mon",
    "2": "Seed Pok\u00e9mon",
    "3": "Lizard Pok\u00e9mon",
    "4": "Flame Pok\u00e9mon"
  },
  "defense": {
    "0": 49,
    "1": 63,
    "2": 123,
    "3": 43,
    "4": 58
  },
  "experience_growth": {
    "0": 1059860,
    "1": 1059860,
    "2": 1059860,
    "3": 1059860,
    "4": 1059860
  },
  "height_m": {
    "0": 0.7,
    "1": 1.0,
    "2": 2.0,
    "3": 0.6,
    "4": 1.1
  },
  "hp": {
    "0": 45,
    "1": 60,
    "2": 80,
    "3": 39,
    "4": 58
  },
  "japanese_name": {
    "0": "Fushigidane\u30d5\u30b7\u30ae\u30c0\u30cd",
    "1": "Fushigisou\u30d5\u30b7\u30ae\u30bd\u30a6",
    "2": "Fushigibana\u30d5\u30b7\u30ae\u30d0\u30ca",
    "3": "Hitokage\u30d2\u30c8\u30ab\u30b2",
    "4": "Lizardo\u30ea\u30b6\u30fc\u30c9"
  },
  "name": {
    "0": "Bulbasaur",
    "1": "Ivysaur",
    "2": "Venusaur",
    "3": "Charmander",
    "4": "Charmeleon"
  },
  "percentage_male": {
    "0": 88.1,
    "1": 88.1,
    "2": 88.1,
    "3": 88.1,
    "4": 88.1
  },
  "pokedex_number": {
    "0": 1,
    "1": 2,
    "2": 3,
    "3": 4,
    "4": 5
  },
  "sp_attack": {
    "0": 65,
    "1": 80,
    "2": 122,
    "3": 60,
    "4": 80
  },
  "sp_defense": {
    "0": 65,
    "1": 80,
    "2": 120,
    "3": 50,
    "4": 65
  },
  "speed": {
    "0": 45,
    "1": 60,
    "2": 80,
    "3": 65,
    "4": 80
  },
  "type1": {
    "0": "grass",
    "1": "grass",
    "2": "grass",
    "3": "fire",
    "4": "fire"
  },
  "type2": {
    "0": "poison",
    "1": "poison",
    "2": "poison",
    "3": null,
    "4": null
  },
  "weight_kg": {
    "0": 6.9,
    "1": 13.0,
    "2": 100.0,
    "3": 8.5,
    "4": 19.0
  },
  "generation": {
    "0": 1,
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1
  },
  "is_legendary": {
    "0": 0,
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0
  }
}

In [11]:
# Render the DataFrame to JSON codes
# Display JSON results with IPython.display

# Render
render = df.head().to_json()   # As a demo, here we show only the first 5 rows
print(f"{type(render)=}\nValue:\n{render}\n")  # 'render' is now a JSON string

# Convert from JSON string to JSON object
import json
json_obj = json.loads(render)
print(f"{type(json_obj)=}\nValue:\n{json_obj}\n")  # 'json_obj' is now a JSON object

# Display
# According to https://stackoverflow.com/a/51616614, a pretty JSON display is not available in Jupyter Notebook but in Jupyter Lab
print('Display:')
display( JSON(json_obj) )

type(render)=<class 'str'>
Value:
{"abilities":{"0":"['Overgrow', 'Chlorophyll']","1":"['Overgrow', 'Chlorophyll']","2":"['Overgrow', 'Chlorophyll']","3":"['Blaze', 'Solar Power']","4":"['Blaze', 'Solar Power']"},"against_bug":{"0":1.0,"1":1.0,"2":1.0,"3":0.5,"4":0.5},"against_dark":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_dragon":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_electric":{"0":0.5,"1":0.5,"2":0.5,"3":1.0,"4":1.0},"against_fairy":{"0":0.5,"1":0.5,"2":0.5,"3":0.5,"4":0.5},"against_fight":{"0":0.5,"1":0.5,"2":0.5,"3":1.0,"4":1.0},"against_fire":{"0":2.0,"1":2.0,"2":2.0,"3":0.5,"4":0.5},"against_flying":{"0":2.0,"1":2.0,"2":2.0,"3":1.0,"4":1.0},"against_ghost":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_grass":{"0":0.25,"1":0.25,"2":0.25,"3":0.5,"4":0.5},"against_ground":{"0":1.0,"1":1.0,"2":1.0,"3":2.0,"4":2.0},"against_ice":{"0":2.0,"1":2.0,"2":2.0,"3":0.5,"4":0.5},"against_normal":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_poison":{"0":1.0,"1":1.0,"2":1.0,"3":1.0,"4":1.0},"against_psychic":{"0":2.0,"1":2.0,"2":2.0,"3":1.0,"4":1.0},"against_rock":{"0":1.0,"1":1.0,"2":1.0,"3":2.0,"4":2.0},"against_steel":{"0":1.0,"1":1.0,"2":1.0,"3":0.5,"4":0.5},"against_water":{"0":0.5,"1":0.5,"2":0.5,"3":2.0,"4":2.0},"attack":{"0":49,"1":62,"2":100,"3":52,"4":64},"base_egg_steps":{"0":5120,"1":5120,"2":5120,"3":5120,"4":5120},"base_happiness":{"0":70,"1":70,"2":70,"3":70,"4":70},"base_total":{"0":318,"1":405,"2":625,"3":309,"4":405},"capture_rate":{"0":"45","1":"45","2":"45","3":"45","4":"45"},"classfication":{"0":"Seed Pok\u00e9mon","1":"Seed Pok\u00e9mon","2":"Seed Pok\u00e9mon","3":"Lizard Pok\u00e9mon","4":"Flame Pok\u00e9mon"},"defense":{"0":49,"1":63,"2":123,"3":43,"4":58},"experience_growth":{"0":1059860,"1":1059860,"2":1059860,"3":1059860,"4":1059860},"height_m":{"0":0.7,"1":1.0,"2":2.0,"3":0.6,"4":1.1},"hp":{"0":45,"1":60,"2":80,"3":39,"4":58},"japanese_name":{"0":"Fushigidane\u30d5\u30b7\u30ae\u30c0\u30cd","1":"Fushigisou\u30d5\u30b7\u30ae\u30bd\u30a6","2":"Fushigibana\u30d5\u30b7\u30ae\u30d0\u30ca","3":"Hitokage\u30d2\u30c8\u30ab\u30b2","4":"Lizardo\u30ea\u30b6\u30fc\u30c9"},"name":{"0":"Bulbasaur","1":"Ivysaur","2":"Venusaur","3":"Charmander","4":"Charmeleon"},"percentage_male":{"0":88.1,"1":88.1,"2":88.1,"3":88.1,"4":88.1},"pokedex_number":{"0":1,"1":2,"2":3,"3":4,"4":5},"sp_attack":{"0":65,"1":80,"2":122,"3":60,"4":80},"sp_defense":{"0":65,"1":80,"2":120,"3":50,"4":65},"speed":{"0":45,"1":60,"2":80,"3":65,"4":80},"type1":{"0":"grass","1":"grass","2":"grass","3":"fire","4":"fire"},"type2":{"0":"poison","1":"poison","2":"poison","3":null,"4":null},"weight_kg":{"0":6.9,"1":13.0,"2":100.0,"3":8.5,"4":19.0},"generation":{"0":1,"1":1,"2":1,"3":1,"4":1},"is_legendary":{"0":0,"1":0,"2":0,"3":0,"4":0}}

type(json_obj)=<class 'dict'>
Value:
{'abilities': {'0': "['Overgrow', 'Chlorophyll']", '1': "['Overgrow', 'Chlorophyll']", '2': "['Overgrow', 'Chlorophyll']", '3': "['Blaze', 'Solar Power']", '4': "['Blaze', 'Solar Power']"}, 'against_bug': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 0.5, '4': 0.5}, 'against_dark': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_dragon': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_electric': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 1.0, '4': 1.0}, 'against_fairy': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 0.5, '4': 0.5}, 'against_fight': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 1.0, '4': 1.0}, 'against_fire': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 0.5, '4': 0.5}, 'against_flying': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 1.0, '4': 1.0}, 'against_ghost': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_grass': {'0': 0.25, '1': 0.25, '2': 0.25, '3': 0.5, '4': 0.5}, 'against_ground': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 2.0, '4': 2.0}, 'against_ice': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 0.5, '4': 0.5}, 'against_normal': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_poison': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 1.0, '4': 1.0}, 'against_psychic': {'0': 2.0, '1': 2.0, '2': 2.0, '3': 1.0, '4': 1.0}, 'against_rock': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 2.0, '4': 2.0}, 'against_steel': {'0': 1.0, '1': 1.0, '2': 1.0, '3': 0.5, '4': 0.5}, 'against_water': {'0': 0.5, '1': 0.5, '2': 0.5, '3': 2.0, '4': 2.0}, 'attack': {'0': 49, '1': 62, '2': 100, '3': 52, '4': 64}, 'base_egg_steps': {'0': 5120, '1': 5120, '2': 5120, '3': 5120, '4': 5120}, 'base_happiness': {'0': 70, '1': 70, '2': 70, '3': 70, '4': 70}, 'base_total': {'0': 318, '1': 405, '2': 625, '3': 309, '4': 405}, 'capture_rate': {'0': '45', '1': '45', '2': '45', '3': '45', '4': '45'}, 'classfication': {'0': 'Seed Pokémon', '1': 'Seed Pokémon', '2': 'Seed Pokémon', '3': 'Lizard Pokémon', '4': 'Flame Pokémon'}, 'defense': {'0': 49, '1': 63, '2': 123, '3': 43, '4': 58}, 'experience_growth': {'0': 1059860, '1': 1059860, '2': 1059860, '3': 1059860, '4': 1059860}, 'height_m': {'0': 0.7, '1': 1.0, '2': 2.0, '3': 0.6, '4': 1.1}, 'hp': {'0': 45, '1': 60, '2': 80, '3': 39, '4': 58}, 'japanese_name': {'0': 'Fushigidaneフシギダネ', '1': 'Fushigisouフシギソウ', '2': 'Fushigibanaフシギバナ', '3': 'Hitokageヒトカゲ', '4': 'Lizardoリザード'}, 'name': {'0': 'Bulbasaur', '1': 'Ivysaur', '2': 'Venusaur', '3': 'Charmander', '4': 'Charmeleon'}, 'percentage_male': {'0': 88.1, '1': 88.1, '2': 88.1, '3': 88.1, '4': 88.1}, 'pokedex_number': {'0': 1, '1': 2, '2': 3, '3': 4, '4': 5}, 'sp_attack': {'0': 65, '1': 80, '2': 122, '3': 60, '4': 80}, 'sp_defense': {'0': 65, '1': 80, '2': 120, '3': 50, '4': 65}, 'speed': {'0': 45, '1': 60, '2': 80, '3': 65, '4': 80}, 'type1': {'0': 'grass', '1': 'grass', '2': 'grass', '3': 'fire', '4': 'fire'}, 'type2': {'0': 'poison', '1': 'poison', '2': 'poison', '3': None, '4': None}, 'weight_kg': {'0': 6.9, '1': 13.0, '2': 100.0, '3': 8.5, '4': 19.0}, 'generation': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}, 'is_legendary': {'0': 0, '1': 0, '2': 0, '3': 0, '4': 0}}

Display:

# PRACTICE

https://www.w3resource.com/python-exercises/pandas/movies/index.php